### ISSUE TITLE
Writing computed properties

### ISSUE THREAD

**Issue by lexa7979** [hitchyjs/plugin-odem-rest#3]
**Situation**

I defined a model with a computed property which handles write-actions, too:

```
module.exports = {
    props: {
        stateEnum: { type: "number" }
    },
    computeds: {
        state( caption ) {
            if ( caption == null ) {
                return this.stateEnum === 1 ? "finished" : "processing";
            }
            this.stateEnum = caption === "finished" ? 1 : 0;
        }
    }
}
```

**Problem**

When I use the standard REST-API from hitchy-plugin-odem-rest, I can read the computed property *state*, but I'm not able to change it's value.

**Comment by soletan** [comment]
The provided fix for the issue has been revised, adopted in published in v0.2.4.
